// Code generated by blueprint_index_gen. DO NOT EDIT.

//go:build embed

//nolint

package blueprint

import (
	"os"
	"syscall"
	"magalu.cloud/core/dataloader"
)

type embedLoader map[string][]byte

func GetEmbedLoader() dataloader.Loader {
	return embedLoaderInstance
}

func (f embedLoader) Load(name string) ([]byte, error) {
	if data, ok := embedLoaderInstance[name]; ok {
		return data, nil
	}
	return nil, &os.PathError{Op: "open", Path: name, Err: syscall.ENOENT}
}

func (f embedLoader) String() string {
	return "embedLoader"
}

var embedLoaderInstance = embedLoader{
	"index.blueprint.yaml": ([]byte)("{\"modules\":[],\"version\":\"1.0.0\"}"),
}
